namespace War
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        /// <author>Zach Biggs - All code in this project is my own or auto generated by the
        /// IDE. I learned via the Microsoft C# documentation and didn't take any code from anybody else.
        /// I did not use Stackoverflow, Github, or anything like that.</author>
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Application.Run(new Form1());
        }
    }
}